# CIS 731 - Assignment 2
# Dharanidharan Ramasamy Karuppanasamy
# SUID : 320028178

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [17]:
traindata=pd.read_excel('ANNdataset (1).xlsx', sheet_name='Train')

In [18]:
traindata=traindata.dropna()
from sklearn.model_selection import train_test_split
train,test= train_test_split(traindata,test_size=0.3)

In [19]:
train_op = train['output']
train_ip = train.drop(['output','education'],axis = 1)

In [20]:
test_op = test['output']
test_ip = test.drop(['output','education'],axis = 1)

In [21]:
train_ip.shape

(21112, 13)

# Got training and test dataset. Now we need to do one hot encoding on both train and test data inorder to change the categorical values to numercial values.

In [22]:
train_nn_ip = pd.get_dummies(train_ip)
test_nn_ip = pd.get_dummies(test_ip)

In [23]:
print(len(list(train_nn_ip.columns)))

87


In [24]:
print(len(list(test_nn_ip.columns)))

87


# The dataset for training and testing is here. Now we need to normalise both train and test data to scale all the features.

In [25]:
sc = StandardScaler()
X_train = sc.fit_transform(train_nn_ip)
X_test = sc.transform(test_nn_ip)

In [25]:
import tensorflow as tf
from tensorflow import keras

/Users/Siddarth/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/Users/Siddarth/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [26]:
model = keras.Sequential([keras.layers.Dense(174,input_dim=87,activation=tf.nn.sigmoid),keras.layers.Dense(1),])
model.compile(optimizer='SGD',loss='mse',metrics=['accuracy'])
model.fit(X_train,train_op,validation_data=(X_test,test_op),epochs=50)

In [36]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
pred  = model.predict(X_test, verbose=1)
predictions = (pred > 0.5)
labels = (test_op == 1)

print(confusion_matrix(predictions,labels))


9049/9049 [==============================] - 0s 22us/step
[[6199  732]
 [ 604 1514]]


In [ ]:
from keras import optimizers
from keras.models import Sequential
from keras.layers import Dense,Activation
from keras.optimizers import SGD
model1=keras.Sequential([keras.layers.Dense(174,input_dim=87,activation=tf.nn.sigmoid),keras.layers.Dense(1),])

sgd = SGD(lr=0.5, decay=1e-6, momentum=0.0, nesterov=True)
model1.compile(loss='mean_squared_error', optimizer='sgd')
model1.fit(X_train,train_op,validation_data=(X_test,test_op),epochs=50)

In [97]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
pred  = model1.predict(X_test, verbose=1)
predictions = (pred >= 0.5)
labels = (test_op == 1)

print(confusion_matrix(predictions,labels))

9049/9049 [==============================] - 0s 48us/step
[[6630 1325]
 [ 173  921]]


In [ ]:
import keras
import tensorflow as tf
from keras import optimizers
from keras.models import Sequential
from keras.layers import Dense,Activation
from keras.optimizers import SGD
model2= keras.Sequential([keras.layers.Dense(174,input_dim=87,activation=tf.nn.sigmoid),keras.layers.Dense(1),])

sgd = SGD(lr=0.3, decay=1e-6, momentum=0.0, nesterov=True)
model2.compile(loss='mean_squared_error', optimizer='sgd')
model2.fit(X_train,train_op,validation_data=(X_test,test_op),epochs=50)

In [29]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
pred  = model2.predict(X_test, verbose=1)
predictions = (pred >= 0.5)
labels = (test_op == 1)

print(confusion_matrix(predictions,labels))

9049/9049 [==============================] - 0s 22us/step
[[6675 1585]
 [ 112  677]]


In [ ]:
import keras
import tensorflow as tf
from keras import optimizers
from keras.models import Sequential
from keras.layers import Dense,Activation
from keras.optimizers import SGD
model3= keras.Sequential([keras.layers.Dense(174,input_dim=87,activation=tf.nn.sigmoid),keras.layers.Dense(1),])

sgd = SGD(lr=1, decay=1e-6, momentum=0.0, nesterov=True)
model3.compile(loss='mean_squared_error', optimizer='sgd')
model3.fit(X_train,train_op,validation_data=(X_test,test_op),epochs=50)

In [36]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
pred  = model3.predict(X_test, verbose=1)
predictions = (pred >= 0.5)
labels = (test_op == 1)

print(confusion_matrix(predictions,labels))

9049/9049 [==============================] - 0s 26us/step
[[6612 1378]
 [ 175  884]]
